### ISSUE TITLE
Suggestions/comments after trying umake

### ISSUE THREAD

**Issue by pherralis** [grisha85/umake#22]
Hello,
This project seems really interesting!  After just playing around with it for fun i want to suggest a few things I came across as confusing / frustrating.

1. If a glob expands to nothing (ie files not found) it would be nice if there was some warning about this, rather than the next step just failing
2. https://github.com/grisha85/dpdk/blob/master/UMakefile is sort of a weird example to point people towards, especially since it appears to be autogenerated (also the foreach calls on single targets made no sense to me until i realized it was autogenerated).   Without a more extensive real life example it's sort of hard to get started.

**Comment by grisha85** [comment]
1. It's a matter of perspective. I like to treat warnings as error
2.It's mentioned in the documentation that it is autogenerated and not an example of best practice.
2.1. Best practice would be added

**Comment by pherralis** [comment]
what would cause:
```
Traceback (most recent call last):
  File "/usr/local/bin/umake", line 1678, in <module>
    umake.run()
  File "/usr/local/bin/umake", line 1476, in run
    self.execute_graph()
  File "/usr/local/bin/umake", line 1423, in execute_graph
    self._handle_done(add_conns, del_conns)
  File "/usr/local/bin/umake", line 1316, in _handle_done
raise RuntimeError(f"Target not generated: Expected {self.target} Got: {self.dep_files}")
```
to be triggered? I can build 'some' targets in my test project, so it's weird that i'm getting this for just one (I don't really know strace unfortunately) (so far).  The .o files i'm generating appear to be generating the correct binaries that I desire.

**Comment by grisha85** [comment]
Thanks for your replies. could you attach your UMakefile, that I could check?
But usually this happens due to typo in the target / or wrong directory.

**Comment by pherralis** [comment]
sorry I don't think i gave enough information!
umake is 'somewhat?' working fine, the problem appears to be strace
my command is basically:
```
!default_compile(flags, includes, defines): /bin/mkdir -p umake/build{dir} && g++ -c {filename}  $defines $includes $flags -o {target}
:foreach utils/**/*.cc > !default_compile($default_flags, $default_includes, $default_defines) > umake/build{dir}/{noext}.o
```
(i'm excluding the $ because it's private, but i can include snippits if necessary)

given the following for loop:
```
while true;
do
    do rm xxxxxx \
    && rm mytarget.o \
    && strace -o xxxxxx -f -e open,openat /bin/bash -c 'g++ -c {path_to_cc_file}/ControlRoom.cc $defines $includes $flags -o mytarget.o \
    && grep ControlRoom xxxxxx;
done
```
i get results that look like:
```
...
3820  openat(AT_FDCWD, "utils/hello/ControlRoom.o", O_RDWR|O_CREAT|O_TRUNC, 0666 <unfinished ...>
...
...
3820  openat(AT_FDCWD, "utils/hello/ControlRoom.o", O_RDWR|O_CREAT|O_TRUNC, 0666) = 3
...
...
3820  openat(AT_FDCWD, "utils/hello/ControlRoom.o", O_RDWR|O_CREAT|O_TRUNC, 0666 <unfinished ...>
...
...
3820  openat(AT_FDCWD, "utils/hello/ControlRoom.o", O_RDWR|O_CREAT|O_TRUNC, 0666) = 3
...
...
3820  openat(AT_FDCWD, "utils/hello/ControlRoom.o", O_RDWR|O_CREAT|O_TRUNC, 0666) = 3
...
```

so strace seems to randomly be unfinishing its commands..s What could be the cause of that?

**Comment by pherralis** [comment]
The problem appears to be that... for some reason the `/bin/bash -c 'g++...` call is being made with multiple threads somehow? I'm not exactly sure why, but running with  strace -ff, and then collecting all output files (in the above example this would be xxxxxx.12345 xxxxxx.22345 xxxxxx.32345 etc....) and grepping those, i never see unfinished.... how strange

**Comment by oshamash** [comment]
@grisha85 
Seems like @pherralis is on the mark, we use `strace -f` which tracks the child-processes, but not the child's child-processes

Interesting option from man-page:
```
       -o filename Write  the  trace  output to the file filename rather than to stderr.  filename.pid form is used if -ff option is supplied.  If the argument begins with '|' or '!', the rest of the argument is treated as a command
                   and all output is piped to it.  This is convenient for piping the debugging output to a program without affecting the redirections of executed programs.  The latter is not compatible with -ff option currently.
```
We can try using the `|` or` !` option to pipeline all using `strace -ff` so that we handle those cases where the command forks in a single file

**Comment by grishaf** [comment]
I had an issue with `-pipe` command with gcc, you might using  it?

**Comment by pherralis** [comment]
I am indeed using the -pipe command with gcc! removing that appears to fix a ton of the problems/errors i was getting!
